name: "Digital Alchemy"
description: "Digital Alchemy deployment runner"
version: "1.0.0"
slug: "digital_alchemy"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  app_root: /config/home_automation
  config_file: "/config/test"
  mode: deploy

schema:
  app_root: str
  config_file: str
  mode: list(deploy|run|watch)

map:
  - config:rw
