name: "Digital Alchemy"
description: "Digital Alchemy deployment runner"
version: "24.7.1"
slug: "digital_alchemy"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  app_root: /config/home_automation
  env_file: ""
  mode: deploy

schema:
  app_root: str
  env_file: str
  mode: list(deploy|watch)

map:
  - config:rw
